### ISSUE TITLE
OpenID Connect Enhancements

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk#4013]
List of open issues/enhancements needed for OpenID Connect integrations to work properly. I hope with this developer find it easier to track and work on development on this.

- [ ] unable to Login with OpenID Connect if i had already signup with SSO with the same email and sub https://github.com/coralproject/talk/issues/3198
- [ ] no process to merge or manage users that use different login methods SSO/OIDC https://github.com/coralproject/talk/issues/3198#issuecomment-703878394
- [ ] INTERNAL_ERROR: DUPLICATE_EMAIL with OpenID Connect https://github.com/coralproject/talk/issues/3842
- [ ] Make the register window larger (OpenID Connect) https://github.com/coralproject/talk/issues/3839
- [ ] DUPLICATE_USER error in this case: user creation via SSO, and then deletion, and then creation again via SSO https://github.com/coralproject/talk/issues/3243
- [ ] Account linking doesn't work with OIDC https://github.com/coralproject/talk/issues/3947
- [ ] Update User Badge while using SSO https://github.com/coralproject/talk/issues/3838 
- [ ] External user profile URL configuration https://github.com/coralproject/talk/pull/3891
- [ ] Email address verification should be disabled while using only OpenID Connect https://github.com/coralproject/talk/issues/3843
- [ ] Automatically redirect to Signup with only OpenID Connect enabled https://github.com/coralproject/talk/issues/3853
- [ ] Unable to delete account(OIDC) https://github.com/coralproject/talk/issues/3840
- [ ] "INTERNAL_ERROR: DUPLICATE_EMAIL" after moving to SSO https://github.com/coralproject/talk/issues/3976
- [ ] Duplicate usernames permitted by E-Mail Authentication https://github.com/coralproject/talk/issues/3941
